name: Build iOS

on:
  workflow_dispatch:
  push:
    branches:
      - "angelosorte.github.io"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Kotlin Multiplatform iOS framework
        run: ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64

      - name: Build iOS app
        working-directory: iosApp
        run: |
          xcodebuild \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            build
